### ISSUE TITLE
[Appreciation] Giving thanks & Suggestion for modpack creators

### ISSUE THREAD

**Issue by Cixon** [IAFEnvoy/IceAndFire-Fabric#45]
### Thank you

I just want to say, I really appreciate all your time and dedication to this port, this mod works splendidly well with my modpack and I cannot thank you enough, I cannot wait to see more updates in the future! You're amazing! 😊

### Suggestion:

If there were one thing I would recommend out of everything for this port is to allow modpack creators to properly edit the Dragon Rooster spawns more effectively using datapacks.

An example of this is using the `worldgen\structure_set` feature, it will allow for changes like this:

```

{
  "placement": {
    "type": "minecraft:random_spread",
    "exclusion_zone": {
      "chunk_count": 32,
      "other_set": "iceandfire:dragon_roost"
    },
    "frequency": 0.1,
    "frequency_reduction_method": "legacy_type_3",
    "salt": 165745296,
    "separation": 16,
    "spacing": 22
  },
  "structures": [
    {
      "structure": "iceandfire:fire_dragon_roost",
      "weight": 1
    }
  ]
}


```

If this suggestion is not possible on your end or just not in your best interest, may we have more options for the `tags\worldgen\biome\structure_gen` and `iaf-common.json` such as editing chunk distances for roosts?

There's a issue right now where they're inconsistent which is sometimes nice but often times you'll come across more than 1 roost within a close distance of one another.

**Comment by IAFEnvoy** [comment]
Since dragon roost is not a structure but a world feature, i dont know how to add such datapack system.

Also spawn chance and spawn biome is enough i think.

**Comment by SiverDX** [comment]
There is a `FeaturePoolElement` (it's used for villages, e.g. `SnowyVillagePools`)
Example: https://github.com/misode/mcmeta/blob/1.20.1-data/data/minecraft/worldgen/template_pool/village/snowy/trees.json

**Comment by Cixon** [comment]
> There is a `FeaturePoolElement` (it's used for villages, e.g. `SnowyVillagePools`)
> Example: https://github.com/misode/mcmeta/blob/1.20.1-data/data/minecraft/worldgen/template_pool/village/snowy/trees.json

If utilized, could datapack creators use this to edit the distances or just weights?
Weights don’t really do much but tell Minecraft what to prioritize..I feel the feature pool doesn’t allow the same changes you could apply for structures such as `exclusion_zone`

**Comment by SiverDX** [comment]
a pool element is part of a structure (and therefor structure set)

1. structure set references structure
2. structure references a `start_pool` (e.g. https://github.com/misode/mcmeta/blob/1.20.1-data/data/minecraft/worldgen/template_pool/village/snowy/town_centers.json)
3. said pool references possible structure nbts to spawn / start with
4. the structure nbt has jigsaw blocks with a pool element (e.g. said feature pool element)

see https://minecraft.wiki/w/Jigsaw_structure

**Comment by SiverDX** [comment]
Example:

![image](https://github.com/user-attachments/assets/4e219754-1903-4d24-8140-9b10bf2d4bb3)

Places an entry of decor (https://github.com/misode/mcmeta/blob/1.20.1-data/data/minecraft/worldgen/template_pool/village/snowy/decor.json) which may contain a feature (e.g. snow pile)

**Comment by IAFEnvoy** [comment]
This way can only generate fixed structures. Dragon caves is a dynamic generation

**Comment by SiverDX** [comment]
No, this way it generates (places) a feature -> dragon caves are features

**Comment by Cixon** [comment]
soo, is this possible or planned, please? 👀 @IAFEnvoy

**Comment by IAFEnvoy** [comment]
planned, i also want to rewrite the whole generate system

**Comment by Cixon** [comment]
> planned, i also want to rewrite the whole generate system

pogchamp. i worry this may corrupt old worlds, hopefully not! 🤞 
i kinda rely on this mod for my neoforge pack; the forge IAF mod doesn’t generate dragon roosts and other structures on my modded world-generation.

Modpack here:
https://modrinth.com/modpack/beta-rpg
