### ISSUE TITLE
[Read Before Report] Structure related issues.

### ISSUE THREAD

**Issue by IAFEnvoy** [IAFEnvoy/IceAndFire-Fabric#49]
As IAF Forge using feature instead of structure to generate some structures, this may cause a lot of bugs. We are trying to fix.

Most of the bugs caused by dragon caves.

## The bugs may meet

- Dragon caves look like being "cut": Features have a generate size limit of 3x3 chunks.
- Distance Horizon will spam the log and cause generating failure. (#33)
- Cannot edit structure generation through datapacks. (#45)

**Comment by GabrielaKelly** [comment]
also crashes server

**Comment by IAFEnvoy** [comment]
0.7-alpha1 have published, you can have a test now

**Comment by IAFEnvoy** [comment]
0.7 released and totally rewrite structures. Should fix these issues.
