### ISSUE TITLE
QUESTION: Distance and quantity

### ISSUE THREAD

**Issue by BernardoGrigiastro** [IAFEnvoy/IceAndFire-Fabric#58]
### What had happened?

Way too many pixies and dragons

*What you have done and what happen*

Played my pack :) 
The dragons are TOO close from each other, it feels like i'm playing rlcraft without even needing the other mob mods to kill me, i can barely move without being spotted and killed by a dragon multiple times and i am only talking the surface ones and pixies spawn everywhere in large groups.
That said... how can i fix both things?

### Mod Version (Include dependencies)

Ice and Fire 0.7
Jupiter 2.0
Uranus 1.7.1

### Mod Loader Version

Fabric 0.16.9

### Game Log

*Recommended to upload it onto mclo.gs, pastebin and so on.*

### Checklist

- [x] I don't install Optifine
- [x] I have installed other mods

**Comment by IAFEnvoy** [comment]
you can adjust yourself by using datapacks. now every structure are controlled like the vanilla ones

**Comment by BernardoGrigiastro** [comment]
Yeah I thought so but even tho I somewhat know how to use datapacks I have no idea which parameters to change so that they are not so close to each other. 
What about the pixies?

**Comment by IAFEnvoy** [comment]
https://minecraft.wiki/w/Tutorials/Custom_structures

![image](https://github.com/user-attachments/assets/f4af53bb-0116-4438-ae79-746416148188)

You can check it out in mc wiki.

**Comment by BernardoGrigiastro** [comment]
Thx, I did that but i dont know what separation and spacing means as by the name they are the same thing to me
But pixies have a structure they should only spawn at??? I see them everywhere...

**Comment by IAFEnvoy** [comment]
Too many structures maybe, in the code it will only generate with structure.
