### ISSUE TITLE
port to neoforge 1.21.1?

### ISSUE THREAD

**Issue by VaporeonScripts** [IAFEnvoy/IceAndFire-Fabric#59]
### Mod Loader Version neoforge 1.21.1 .77
- [ ofc lol] I don't install Optifine
- [ got nothing to do with this] I have installed other mods

**Comment by IAFEnvoy** [comment]
fabric is planned to make 1.21.1

i'm waiting for Alex's response before port to neoforge

**Comment by VaporeonScripts** [comment]
Alright
